GET https://api-6xr77bk9.an.gateway.dev/recipe

GET https://recipeservice-ewzql6uxba-uc.a.run.app/feed

###
GET https://recipeservice-ewzql6uxba-uc.a.run.app/recipe

###
GET https://api-6xr77bk9.an.gateway.dev/recipe/32

###
POST  https://api-6xr77bk9.an.gateway.dev/recipe
Content-Type: application/json

{
    "name": "SOMTUM",
    "description":"ZAAP NUA",
    "image_url": null,
    "user_id": "635ba528e9199de9c3726aca",
    "user": {
      "user_id": "635ba528e9199de9c3726aca",
      "fullname": "Fair Weerapat"
    },
    "ingrediants": [
      {
        "name": null,
        "amount": null,
        "unit": null
      }
    ],
    "instructions": [],
    "tools": [
      {
        "tool": null
      }
    ]
}

###
DELETE https://api-6xr77bk9.an.gateway.dev/recipe/30

###
PUT  https://api-6xr77bk9.an.gateway.dev/recipe/1
Content-Type: application/json

{
    "name": "Donut",
    "description":"Sweet"
}