GET https://api-6xr77bk9.an.gateway.dev/information

###
GET https://api-6xr77bk9.an.gateway.dev/information/63779ec808c7a025c8653884


###
POST  https://api-6xr77bk9.an.gateway.dev/information
Content-Type: application/json

{
"fullname": "May 3",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}

###
DELETE https://api-6xr77bk9.an.gateway.dev/information/637760d33ebb7754922fcace

###
PUT  https://api-6xr77bk9.an.gateway.dev/information/637760d33ebb7754922fcace
Content-Type: application/json

{
"fullname": "May Chanapa",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}



PUT  https://api-6xr77bk9.an.gateway.dev/information/637760d33ebb7754922fcace
Content-Type: application/json

{
"fullname": "May Chanapa",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}

###
DELETE http://user.cooknet.cf/information/637760d33ebb7754922fcace

###
GET  http://user.cooknet.cf/information/637760d33ebb7754922fcace
Content-Type: application/json

{
"fullname": "May Chanapa",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}



###
GET https://api-6xr77bk9.an.gateway.dev/feedback

###
GET https://recipeservice-ewzql6uxba-uc.a.run.app/recipe

