GET https://api-6xr77bk9.an.gateway.dev/information

###
GET https://api-6xr77bk9.an.gateway.dev/information/635ba528e9199de9c3726aca


###
POST  https://api-6xr77bk9.an.gateway.dev/information
Content-Type: application/json

{
"fullname": "May",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}

###
DELETE https://api-6xr77bk9.an.gateway.dev/information/637760d33ebb7754922fcace

###
PUT  https://api-6xr77bk9.an.gateway.dev/information/637760d33ebb7754922fcace
Content-Type: application/json

{
"fullname": "May Chanapa",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}



PUT  https://api-6xr77bk9.an.gateway.dev/information/637760d33ebb7754922fcace
Content-Type: application/json

{
"fullname": "May Chanapa",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}

###
DELETE http://user.cooknet.cf/information/637760d33ebb7754922fcace

###
PUT  http://user.cooknet.cf/information/637760d33ebb7754922fcace
Content-Type: application/json

{
"fullname": "May Chanapa",
"email": "test@gmail.com",
"phone": "099999999",
"birthday": "1995-03-25"
}